<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LotTagProcessFilesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $list = array(
            ['id'=> 1,'lot_tag_id' => 1,'process_id' => 12],
            ['id'=> 2,'lot_tag_id' => 1,'process_id' => 56],
            ['id'=> 3,'lot_tag_id' => 1,'process_id' => 82],
            ['id'=> 4,'lot_tag_id' => 1,'process_id' => 84],
            ['id'=> 5,'lot_tag_id' => 1,'process_id' => 85],
            ['id'=> 6,'lot_tag_id' => 1,'process_id' => 26],
            ['id'=> 7,'lot_tag_id' => 2,'process_id' => 6],
            ['id'=> 8,'lot_tag_id' => 2,'process_id' => 12],
            ['id'=> 9,'lot_tag_id' => 2,'process_id' => 56],
            ['id'=> 10,'lot_tag_id' => 2,'process_id' => 82],
            ['id'=> 11,'lot_tag_id' => 2,'process_id' => 84],
            ['id'=> 12,'lot_tag_id' => 2,'process_id' => 85],
            ['id'=> 13,'lot_tag_id' => 2,'process_id' => 26],
            ['id'=> 14,'lot_tag_id' => 3,'process_id' => 6],
            ['id'=> 15,'lot_tag_id' => 3,'process_id' => 58],
            ['id'=> 16,'lot_tag_id' => 3,'process_id' => 86],
            ['id'=> 17,'lot_tag_id' => 3,'process_id' => 8],
            ['id'=> 18,'lot_tag_id' => 3,'process_id' => 14],
            ['id'=> 19,'lot_tag_id' => 4,'process_id' => 15],
            ['id'=> 20,'lot_tag_id' => 4,'process_id' => 16],
            ['id'=> 21,'lot_tag_id' => 4,'process_id' => 87],
            ['id'=> 22,'lot_tag_id' => 4,'process_id' => 14],
            ['id'=> 23,'lot_tag_id' => 4,'process_id' => 88],
            ['id'=> 24,'lot_tag_id' => 5,'process_id' => 6],
            ['id'=> 25,'lot_tag_id' => 5,'process_id' => 58],
            ['id'=> 26,'lot_tag_id' => 5,'process_id' => 16],
            ['id'=> 27,'lot_tag_id' => 5,'process_id' => 57],
            ['id'=> 28,'lot_tag_id' => 5,'process_id' => 38],
            ['id'=> 29,'lot_tag_id' => 5,'process_id' => 92],
            ['id'=> 30,'lot_tag_id' => 6,'process_id' => 58],
            ['id'=> 31,'lot_tag_id' => 6,'process_id' => 16],
            ['id'=> 32,'lot_tag_id' => 6,'process_id' => 57],
            ['id'=> 33,'lot_tag_id' => 6,'process_id' => 38],
            ['id'=> 34,'lot_tag_id' => 6,'process_id' => 92],
            ['id'=> 35,'lot_tag_id' => 7,'process_id' => 58],
            ['id'=> 36,'lot_tag_id' => 7,'process_id' => 16],
            ['id'=> 37,'lot_tag_id' => 7,'process_id' => 57],
            ['id'=> 38,'lot_tag_id' => 7,'process_id' => 38],
            ['id'=> 39,'lot_tag_id' => 7,'process_id' => 92],
            ['id'=> 40,'lot_tag_id' => 8,'process_id' => 58],
            ['id'=> 41,'lot_tag_id' => 8,'process_id' => 16],
            ['id'=> 42,'lot_tag_id' => 8,'process_id' => 57],
            ['id'=> 43,'lot_tag_id' => 8,'process_id' => 38],
            ['id'=> 44,'lot_tag_id' => 8,'process_id' => 92],

            ['id'=> 45,'lot_tag_id' => 9,'process_id' => 1],
            ['id'=> 46,'lot_tag_id' => 9,'process_id' => 2],
            ['id'=> 47,'lot_tag_id' => 9,'process_id' => 7],
            ['id'=> 48,'lot_tag_id' => 9,'process_id' => 93],
            ['id'=> 49,'lot_tag_id' => 9,'process_id' => 17],

            ['id'=> 50,'lot_tag_id' => 10,'process_id' => 1],
            ['id'=> 51,'lot_tag_id' => 10,'process_id' => 2],
            ['id'=> 52,'lot_tag_id' => 10,'process_id' => 7],
            ['id'=> 53,'lot_tag_id' => 10,'process_id' => 93],
            ['id'=> 54,'lot_tag_id' => 10,'process_id' => 17],

            ['id'=> 55,'lot_tag_id' => 11,'process_id' => 1],
            ['id'=> 56,'lot_tag_id' => 11,'process_id' => 2],
            ['id'=> 57,'lot_tag_id' => 11,'process_id' => 7],
            ['id'=> 58,'lot_tag_id' => 11,'process_id' => 93],
            ['id'=> 59,'lot_tag_id' => 11,'process_id' => 47],
            ['id'=> 60,'lot_tag_id' => 11,'process_id' => 17],

            ['id'=> 61,'lot_tag_id' => 12,'process_id' => 1],
            ['id'=> 62,'lot_tag_id' => 12,'process_id' => 2],
            ['id'=> 63,'lot_tag_id' => 12,'process_id' => 7],
            ['id'=> 64,'lot_tag_id' => 12,'process_id' => 93],
            ['id'=> 65,'lot_tag_id' => 12,'process_id' => 47],
            ['id'=> 66,'lot_tag_id' => 12,'process_id' => 17],

            ['id'=> 67,'lot_tag_id' => 13,'process_id' => 1],
            ['id'=> 68,'lot_tag_id' => 13,'process_id' => 2],
            ['id'=> 69,'lot_tag_id' => 13,'process_id' => 7],
            ['id'=> 70,'lot_tag_id' => 13,'process_id' => 93],
            ['id'=> 71,'lot_tag_id' => 13,'process_id' => 47],
            ['id'=> 72,'lot_tag_id' => 13,'process_id' => 17],

            ['id'=> 73,'lot_tag_id' => 14,'process_id' => 1],
            ['id'=> 74,'lot_tag_id' => 14,'process_id' => 2],
            ['id'=> 75,'lot_tag_id' => 14,'process_id' => 7],
            ['id'=> 76,'lot_tag_id' => 14,'process_id' => 93],
            ['id'=> 77,'lot_tag_id' => 14,'process_id' => 47],
            ['id'=> 78,'lot_tag_id' => 14,'process_id' => 17],

            ['id'=> 79,'lot_tag_id' => 15,'process_id' => 1],
            ['id'=> 80,'lot_tag_id' => 15,'process_id' => 28],
            ['id'=> 81,'lot_tag_id' => 15,'process_id' => 29],
            ['id'=> 82,'lot_tag_id' => 15,'process_id' => 30],
            ['id'=> 83,'lot_tag_id' => 15,'process_id' => 31],
            ['id'=> 84,'lot_tag_id' => 15,'process_id' => 32],
            ['id'=> 85,'lot_tag_id' => 15,'process_id' => 33],
            ['id'=> 86,'lot_tag_id' => 15,'process_id' => 9],

            ['id'=> 87,'lot_tag_id' => 16,'process_id' => 1],
            ['id'=> 88,'lot_tag_id' => 16,'process_id' => 28],
            ['id'=> 89,'lot_tag_id' => 16,'process_id' => 29],
            ['id'=> 90,'lot_tag_id' => 16,'process_id' => 30],
            ['id'=> 91,'lot_tag_id' => 16,'process_id' => 31],
            ['id'=> 92,'lot_tag_id' => 16,'process_id' => 32],
            ['id'=> 93,'lot_tag_id' => 16,'process_id' => 33],
            ['id'=> 94,'lot_tag_id' => 16,'process_id' => 9],

            ['id'=> 95,'lot_tag_id' => 17,'process_id' => 58],
            ['id'=> 96,'lot_tag_id' => 17,'process_id' => 8],
            ['id'=> 97,'lot_tag_id' => 17,'process_id' => 86],
            ['id'=> 98,'lot_tag_id' => 17,'process_id' => 18],

            ['id'=> 99,'lot_tag_id' => 18,'process_id' => 58],
            ['id'=> 100,'lot_tag_id' => 18,'process_id' => 8],
            ['id'=> 101,'lot_tag_id' => 18,'process_id' => 86],
            ['id'=> 102,'lot_tag_id' => 18,'process_id' => 18],

            ['id'=> 103,'lot_tag_id' => 19,'process_id' => 6],
            ['id'=> 104,'lot_tag_id' => 19,'process_id' => 2],
            ['id'=> 105,'lot_tag_id' => 19,'process_id' => 56],
            ['id'=> 106,'lot_tag_id' => 19,'process_id' => 13],
            ['id'=> 107,'lot_tag_id' => 19,'process_id' => 24],

            ['id'=> 108,'lot_tag_id' => 20,'process_id' => 6],
            ['id'=> 109,'lot_tag_id' => 20,'process_id' => 2],
            ['id'=> 110,'lot_tag_id' => 20,'process_id' => 56],
            ['id'=> 111,'lot_tag_id' => 20,'process_id' => 13],
            ['id'=> 112,'lot_tag_id' => 20,'process_id' => 24],

            ['id'=> 113,'lot_tag_id' => 21,'process_id' => 1],
            ['id'=> 114,'lot_tag_id' => 21,'process_id' => 12],
            ['id'=> 115,'lot_tag_id' => 21,'process_id' => 7],
            ['id'=> 116,'lot_tag_id' => 21,'process_id' => 94],
            ['id'=> 117,'lot_tag_id' => 21,'process_id' => 13],

            ['id'=> 118,'lot_tag_id' => 22,'process_id' => 26],
            ['id'=> 119,'lot_tag_id' => 22,'process_id' => 41],
            ['id'=> 120,'lot_tag_id' => 22,'process_id' => 42],

            ['id'=> 121,'lot_tag_id' => 23,'process_id' => 15],
            ['id'=> 122,'lot_tag_id' => 23,'process_id' => 22],
            ['id'=> 123,'lot_tag_id' => 23,'process_id' => 95],
            ['id'=> 124,'lot_tag_id' => 23,'process_id' => 14],
            ['id'=> 125,'lot_tag_id' => 23,'process_id' => 96],

            ['id'=> 126,'lot_tag_id' => 24,'process_id' => 15],
            ['id'=> 127,'lot_tag_id' => 24,'process_id' => 22],
            ['id'=> 128,'lot_tag_id' => 24,'process_id' => 95],
            ['id'=> 129,'lot_tag_id' => 24,'process_id' => 14],
            ['id'=> 130,'lot_tag_id' => 24,'process_id' => 96],

            ['id'=> 131,'lot_tag_id' => 25,'process_id' => 1],
            ['id'=> 132,'lot_tag_id' => 25,'process_id' => 16],
            ['id'=> 133,'lot_tag_id' => 25,'process_id' => 97],
            ['id'=> 134,'lot_tag_id' => 25,'process_id' => 8],
            ['id'=> 135,'lot_tag_id' => 25,'process_id' => 59],

            ['id'=> 136,'lot_tag_id' => 26,'process_id' => 1],
            ['id'=> 137,'lot_tag_id' => 26,'process_id' => 16],
            ['id'=> 138,'lot_tag_id' => 26,'process_id' => 97],
            ['id'=> 139,'lot_tag_id' => 26,'process_id' => 8],
            ['id'=> 140,'lot_tag_id' => 26,'process_id' => 59],

            ['id'=> 141,'lot_tag_id' => 27,'process_id' => 1],
            ['id'=> 142,'lot_tag_id' => 27,'process_id' => 12],
            ['id'=> 143,'lot_tag_id' => 27,'process_id' => 7],
            ['id'=> 144,'lot_tag_id' => 27,'process_id' => 94],
            ['id'=> 145,'lot_tag_id' => 27,'process_id' => 13],

            ['id'=> 146,'lot_tag_id' => 28,'process_id' => 1],
            ['id'=> 147,'lot_tag_id' => 28,'process_id' => 28],
            ['id'=> 148,'lot_tag_id' => 28,'process_id' => 29],
            ['id'=> 149,'lot_tag_id' => 28,'process_id' => 30],
            ['id'=> 150,'lot_tag_id' => 28,'process_id' => 31],
            ['id'=> 151,'lot_tag_id' => 28,'process_id' => 32],
            ['id'=> 152,'lot_tag_id' => 28,'process_id' => 98],
            ['id'=> 153,'lot_tag_id' => 28,'process_id' => 9],

            ['id'=> 154,'lot_tag_id' => 29,'process_id' => 15],
            ['id'=> 155,'lot_tag_id' => 29,'process_id' => 22],
            ['id'=> 156,'lot_tag_id' => 29,'process_id' => 8],
            ['id'=> 157,'lot_tag_id' => 29,'process_id' => 24],
            ['id'=> 158,'lot_tag_id' => 29,'process_id' => 47],

            ['id'=> 159,'lot_tag_id' => 30,'process_id' => 15],
            ['id'=> 160,'lot_tag_id' => 30,'process_id' => 16],
            ['id'=> 161,'lot_tag_id' => 30,'process_id' => 27],
            ['id'=> 162,'lot_tag_id' => 30,'process_id' => 45],

            ['id'=> 163,'lot_tag_id' => 31,'process_id' => 15],
            ['id'=> 164,'lot_tag_id' => 31,'process_id' => 16],
            ['id'=> 165,'lot_tag_id' => 31,'process_id' => 8],
            ['id'=> 166,'lot_tag_id' => 31,'process_id' => 18],

            ['id'=> 167,'lot_tag_id' => 32,'process_id' => 15],
            ['id'=> 168,'lot_tag_id' => 32,'process_id' => 16],
            ['id'=> 169,'lot_tag_id' => 32,'process_id' => 8],
            ['id'=> 170,'lot_tag_id' => 32,'process_id' => 18],

            ['id'=> 171,'lot_tag_id' => 33,'process_id' => 1],
            ['id'=> 172,'lot_tag_id' => 33,'process_id' => 2],
            ['id'=> 173,'lot_tag_id' => 33,'process_id' => 7],
            ['id'=> 174,'lot_tag_id' => 33,'process_id' => 93],
            ['id'=> 175,'lot_tag_id' => 33,'process_id' => 17],

            ['id'=> 176,'lot_tag_id' => 34,'process_id' => 1],
            ['id'=> 177,'lot_tag_id' => 34,'process_id' => 2],
            ['id'=> 178,'lot_tag_id' => 34,'process_id' => 99],
            ['id'=> 179,'lot_tag_id' => 34,'process_id' => 86],
            ['id'=> 180,'lot_tag_id' => 34,'process_id' => 100],

            ['id'=> 181,'lot_tag_id' => 35,'process_id' => 15],
            ['id'=> 182,'lot_tag_id' => 35,'process_id' => 101],
            ['id'=> 183,'lot_tag_id' => 35,'process_id' => 82],
            ['id'=> 184,'lot_tag_id' => 35,'process_id' => 59],

            ['id'=> 185,'lot_tag_id' => 36,'process_id' => 15],
            ['id'=> 186,'lot_tag_id' => 36,'process_id' => 101],
            ['id'=> 187,'lot_tag_id' => 36,'process_id' => 82],
            ['id'=> 188,'lot_tag_id' => 36,'process_id' => 59],

            ['id'=> 189,'lot_tag_id' => 37,'process_id' => 15],
            ['id'=> 190,'lot_tag_id' => 37,'process_id' => 79],
            ['id'=> 191,'lot_tag_id' => 37,'process_id' => 102],

            ['id'=> 192,'lot_tag_id' => 38,'process_id' => 15],
            ['id'=> 193,'lot_tag_id' => 38,'process_id' => 79],
            ['id'=> 194,'lot_tag_id' => 38,'process_id' => 102],

            ['id'=> 195,'lot_tag_id' => 39,'process_id' => 1],
            ['id'=> 196,'lot_tag_id' => 39,'process_id' => 2],
            ['id'=> 197,'lot_tag_id' => 39,'process_id' => 19],
            ['id'=> 198,'lot_tag_id' => 39,'process_id' => 13],
            ['id'=> 199,'lot_tag_id' => 39,'process_id' => 26],
            ['id'=> 200,'lot_tag_id' => 39,'process_id' => 27],

            ['id'=> 201,'lot_tag_id' => 40,'process_id' => 6],
            ['id'=> 202,'lot_tag_id' => 40,'process_id' => 28],
            ['id'=> 203,'lot_tag_id' => 40,'process_id' => 29],
            ['id'=> 204,'lot_tag_id' => 40,'process_id' => 7],
            ['id'=> 205,'lot_tag_id' => 40,'process_id' => 26],
            ['id'=> 206,'lot_tag_id' => 40,'process_id' => 51],

            ['id'=> 207,'lot_tag_id' => 41,'process_id' => 1],
            ['id'=> 208,'lot_tag_id' => 41,'process_id' => 2],
            ['id'=> 209,'lot_tag_id' => 41,'process_id' => 56],
            ['id'=> 210,'lot_tag_id' => 41,'process_id' => 17],
            ['id'=> 211,'lot_tag_id' => 41,'process_id' => 102],

            ['id'=> 212,'lot_tag_id' => 42,'process_id' => 1],
            ['id'=> 213,'lot_tag_id' => 42,'process_id' => 2],
            ['id'=> 214,'lot_tag_id' => 42,'process_id' => 56],
            ['id'=> 215,'lot_tag_id' => 42,'process_id' => 47],
            ['id'=> 216,'lot_tag_id' => 42,'process_id' => 49],
            ['id'=> 217,'lot_tag_id' => 42,'process_id' => 50],

            ['id'=> 218,'lot_tag_id' => 43,'process_id' => 6],
            ['id'=> 219,'lot_tag_id' => 43,'process_id' => 1],
            ['id'=> 220,'lot_tag_id' => 43,'process_id' => 12],
            ['id'=> 221,'lot_tag_id' => 43,'process_id' => 48],
            ['id'=> 222,'lot_tag_id' => 43,'process_id' => 47],
            ['id'=> 223,'lot_tag_id' => 43,'process_id' => 49],
            ['id'=> 224,'lot_tag_id' => 43,'process_id' => 50],

            ['id'=> 225,'lot_tag_id' => 44,'process_id' => 6],
            ['id'=> 226,'lot_tag_id' => 44,'process_id' => 26],
            ['id'=> 227,'lot_tag_id' => 44,'process_id' => 41],
            ['id'=> 228,'lot_tag_id' => 44,'process_id' => 42],

            ['id'=> 229,'lot_tag_id' => 46,'process_id' => 1],
            ['id'=> 230,'lot_tag_id' => 46,'process_id' => 15],
            ['id'=> 231,'lot_tag_id' => 46,'process_id' => 16],
            ['id'=> 232,'lot_tag_id' => 46,'process_id' => 104],
            ['id'=> 233,'lot_tag_id' => 46,'process_id' => 27],
            ['id'=> 234,'lot_tag_id' => 46,'process_id' => 26],

            ['id'=> 235,'lot_tag_id' => 47,'process_id' => 1],
            ['id'=> 236,'lot_tag_id' => 47,'process_id' => 15],
            ['id'=> 237,'lot_tag_id' => 47,'process_id' => 16],
            ['id'=> 238,'lot_tag_id' => 47,'process_id' => 104],
            ['id'=> 239,'lot_tag_id' => 47,'process_id' => 27],
            ['id'=> 240,'lot_tag_id' => 47,'process_id' => 26],

            ['id'=> 241,'lot_tag_id' => 48,'process_id' => 6],
            ['id'=> 242,'lot_tag_id' => 48,'process_id' => 2],
            ['id'=> 243,'lot_tag_id' => 48,'process_id' => 7],
            ['id'=> 244,'lot_tag_id' => 48,'process_id' => 8],
            ['id'=> 245,'lot_tag_id' => 48,'process_id' => 9],
            ['id'=> 246,'lot_tag_id' => 48,'process_id' => 105],
            ['id'=> 247,'lot_tag_id' => 48,'process_id' => 11],

            ['id'=> 248,'lot_tag_id' => 49,'process_id' => 6],
            ['id'=> 249,'lot_tag_id' => 49,'process_id' => 2],
            ['id'=> 250,'lot_tag_id' => 49,'process_id' => 7],
            ['id'=> 251,'lot_tag_id' => 49,'process_id' => 8],
            ['id'=> 252,'lot_tag_id' => 49,'process_id' => 9],
            ['id'=> 253,'lot_tag_id' => 49,'process_id' => 105],
            ['id'=> 254,'lot_tag_id' => 49,'process_id' => 11],

            ['id'=> 255,'lot_tag_id' => 53,'process_id' => 1],
            ['id'=> 256,'lot_tag_id' => 53,'process_id' => 2],
            ['id'=> 257,'lot_tag_id' => 53,'process_id' => 7],
            ['id'=> 258,'lot_tag_id' => 53,'process_id' => 93],
            ['id'=> 259,'lot_tag_id' => 53,'process_id' => 17],

            ['id'=> 260,'lot_tag_id' => 55,'process_id' => 1],
            ['id'=> 261,'lot_tag_id' => 55,'process_id' => 2],
            ['id'=> 262,'lot_tag_id' => 55,'process_id' => 7],
            ['id'=> 263,'lot_tag_id' => 55,'process_id' => 106],
            ['id'=> 264,'lot_tag_id' => 55,'process_id' => 13],
            ['id'=> 265,'lot_tag_id' => 55,'process_id' => 107],

            ['id'=> 266,'lot_tag_id' => 56,'process_id' => 6],
            ['id'=> 267,'lot_tag_id' => 56,'process_id' => 15],
            ['id'=> 268,'lot_tag_id' => 56,'process_id' => 16],
            ['id'=> 269,'lot_tag_id' => 56,'process_id' => 87],
            ['id'=> 270,'lot_tag_id' => 56,'process_id' => 14],
            ['id'=> 271,'lot_tag_id' => 56,'process_id' => 108],

            ['id'=> 272,'lot_tag_id' => 57,'process_id' => 6],
            ['id'=> 273,'lot_tag_id' => 57,'process_id' => 15],
            ['id'=> 274,'lot_tag_id' => 57,'process_id' => 16],
            ['id'=> 275,'lot_tag_id' => 57,'process_id' => 87],
            ['id'=> 276,'lot_tag_id' => 57,'process_id' => 14],
            ['id'=> 277,'lot_tag_id' => 57,'process_id' => 108],

            ['id'=> 278,'lot_tag_id' => 58,'process_id' => 1],
            ['id'=> 279,'lot_tag_id' => 58,'process_id' => 2],
            ['id'=> 280,'lot_tag_id' => 58,'process_id' => 7],
            ['id'=> 281,'lot_tag_id' => 58,'process_id' => 8],
            ['id'=> 282,'lot_tag_id' => 58,'process_id' => 109],
            ['id'=> 283,'lot_tag_id' => 58,'process_id' => 110],
            ['id'=> 284,'lot_tag_id' => 58,'process_id' => 36],
            ['id'=> 285,'lot_tag_id' => 58,'process_id' => 111],

            ['id'=> 286,'lot_tag_id' => 59,'process_id' => 1],
            ['id'=> 287,'lot_tag_id' => 59,'process_id' => 2],
            ['id'=> 288,'lot_tag_id' => 59,'process_id' => 7],
            ['id'=> 289,'lot_tag_id' => 59,'process_id' => 8],
            ['id'=> 290,'lot_tag_id' => 59,'process_id' => 109],
            ['id'=> 291,'lot_tag_id' => 59,'process_id' => 110],
            ['id'=> 292,'lot_tag_id' => 59,'process_id' => 36],
            ['id'=> 293,'lot_tag_id' => 59,'process_id' => 111],

            ['id'=> 294,'lot_tag_id' => 60,'process_id' => 1],
            ['id'=> 295,'lot_tag_id' => 60,'process_id' => 2],
            ['id'=> 296,'lot_tag_id' => 60,'process_id' => 56],
            ['id'=> 297,'lot_tag_id' => 60,'process_id' => 112],
            ['id'=> 298,'lot_tag_id' => 60,'process_id' => 113],
            ['id'=> 299,'lot_tag_id' => 60,'process_id' => 11],

            ['id'=> 300,'lot_tag_id' => 61,'process_id' => 114],
            ['id'=> 301,'lot_tag_id' => 61,'process_id' => 28],
            ['id'=> 302,'lot_tag_id' => 61,'process_id' => 29],
            ['id'=> 303,'lot_tag_id' => 61,'process_id' => 7],
            ['id'=> 304,'lot_tag_id' => 61,'process_id' => 8],
            ['id'=> 305,'lot_tag_id' => 61,'process_id' => 26],
            ['id'=> 306,'lot_tag_id' => 61,'process_id' => 51],

            ['id'=> 307,'lot_tag_id' => 62,'process_id' => 15],
            ['id'=> 308,'lot_tag_id' => 62,'process_id' => 16],
            ['id'=> 309,'lot_tag_id' => 62,'process_id' => 86],
            ['id'=> 310,'lot_tag_id' => 62,'process_id' => 8],
            ['id'=> 311,'lot_tag_id' => 62,'process_id' => 115],

            ['id'=> 312,'lot_tag_id' => 63,'process_id' => 15],
            ['id'=> 313,'lot_tag_id' => 63,'process_id' => 22],
            ['id'=> 314,'lot_tag_id' => 63,'process_id' => 8],
            ['id'=> 315,'lot_tag_id' => 63,'process_id' => 24],
            ['id'=> 316,'lot_tag_id' => 63,'process_id' => 47],
            ['id'=> 317,'lot_tag_id' => 63,'process_id' => 96],

            ['id'=> 318,'lot_tag_id' => 64,'process_id' => 89],
            ['id'=> 319,'lot_tag_id' => 64,'process_id' => 2],
            ['id'=> 320,'lot_tag_id' => 64,'process_id' => 90],
            ['id'=> 321,'lot_tag_id' => 64,'process_id' => 14],
            ['id'=> 322,'lot_tag_id' => 64,'process_id' => 27],
            ['id'=> 323,'lot_tag_id' => 64,'process_id' => 91],

            ['id'=> 324,'lot_tag_id' => 65,'process_id' => 89],
            ['id'=> 325,'lot_tag_id' => 65,'process_id' => 2],
            ['id'=> 326,'lot_tag_id' => 65,'process_id' => 90],
            ['id'=> 327,'lot_tag_id' => 65,'process_id' => 14],
            ['id'=> 328,'lot_tag_id' => 65,'process_id' => 27],
            ['id'=> 329,'lot_tag_id' => 65,'process_id' => 91],

            ['id'=> 330,'lot_tag_id' => 66,'process_id' => 1],
            ['id'=> 331,'lot_tag_id' => 66,'process_id' => 2],
            ['id'=> 332,'lot_tag_id' => 66,'process_id' => 7],
            ['id'=> 333,'lot_tag_id' => 66,'process_id' => 124],
            ['id'=> 334,'lot_tag_id' => 66,'process_id' => 8],

            ['id'=> 335,'lot_tag_id' => 67,'process_id' => 1],
            ['id'=> 336,'lot_tag_id' => 67,'process_id' => 125],
            ['id'=> 337,'lot_tag_id' => 67,'process_id' => 7],
            ['id'=> 338,'lot_tag_id' => 67,'process_id' => 8],
            ['id'=> 339,'lot_tag_id' => 67,'process_id' => 27],
            ['id'=> 340,'lot_tag_id' => 67,'process_id' => 26],
            ['id'=> 341,'lot_tag_id' => 67,'process_id' => 91],

            ['id'=> 342,'lot_tag_id' => 68,'process_id' => 1],
            ['id'=> 343,'lot_tag_id' => 68,'process_id' => 126],
            ['id'=> 344,'lot_tag_id' => 68,'process_id' => 7],
            ['id'=> 345,'lot_tag_id' => 68,'process_id' => 8],
            ['id'=> 346,'lot_tag_id' => 68,'process_id' => 127],

            ['id'=> 347,'lot_tag_id' => 69,'process_id' => 1],
            ['id'=> 348,'lot_tag_id' => 69,'process_id' => 2],
            ['id'=> 349,'lot_tag_id' => 69,'process_id' => 7],
            ['id'=> 350,'lot_tag_id' => 69,'process_id' => 5],
            ['id'=> 351,'lot_tag_id' => 69,'process_id' => 133],
            ['id'=> 352,'lot_tag_id' => 69,'process_id' => 91],

            ['id'=> 353,'lot_tag_id' => 70,'process_id' => 6],
            ['id'=> 354,'lot_tag_id' => 70,'process_id' => 2],
            ['id'=> 355,'lot_tag_id' => 70,'process_id' => 7],
            ['id'=> 356,'lot_tag_id' => 70,'process_id' => 8],
            ['id'=> 357,'lot_tag_id' => 70,'process_id' => 36],
            ['id'=> 358,'lot_tag_id' => 70,'process_id' => 91],

            ['id'=> 359,'lot_tag_id' => 71,'process_id' => 26],
            ['id'=> 360,'lot_tag_id' => 71,'process_id' => 41],
            ['id'=> 361,'lot_tag_id' => 71,'process_id' => 42],
            ['id'=> 362,'lot_tag_id' => 71,'process_id' => 43],

            ['id'=> 363,'lot_tag_id' => 72,'process_id' => 1],
            ['id'=> 364,'lot_tag_id' => 72,'process_id' => 2],
            ['id'=> 365,'lot_tag_id' => 72,'process_id' => 56],
            ['id'=> 366,'lot_tag_id' => 72,'process_id' => 128],
            ['id'=> 367,'lot_tag_id' => 72,'process_id' => 129],
            ['id'=> 368,'lot_tag_id' => 72,'process_id' => 55],

            ['id'=> 369,'lot_tag_id' => 73,'process_id' => 6],
            ['id'=> 370,'lot_tag_id' => 73,'process_id' => 15],
            ['id'=> 371,'lot_tag_id' => 73,'process_id' => 22],
            ['id'=> 372,'lot_tag_id' => 73,'process_id' => 116],
            ['id'=> 373,'lot_tag_id' => 73,'process_id' => 27],
            ['id'=> 374,'lot_tag_id' => 73,'process_id' => 117],

            ['id'=> 375,'lot_tag_id' => 74,'process_id' => 26],
            ['id'=> 376,'lot_tag_id' => 74,'process_id' => 41],
            ['id'=> 377,'lot_tag_id' => 74,'process_id' => 42],
            ['id'=> 378,'lot_tag_id' => 74,'process_id' => 43],

            ['id'=> 379,'lot_tag_id' => 75,'process_id' => 118],
            ['id'=> 380,'lot_tag_id' => 75,'process_id' => 8],
            ['id'=> 381,'lot_tag_id' => 75,'process_id' => 86],
            ['id'=> 382,'lot_tag_id' => 75,'process_id' => 18],

            ['id'=> 383,'lot_tag_id' => 76,'process_id' => 118],
            ['id'=> 384,'lot_tag_id' => 76,'process_id' => 8],
            ['id'=> 385,'lot_tag_id' => 76,'process_id' => 86],
            ['id'=> 386,'lot_tag_id' => 76,'process_id' => 18],

            ['id'=> 387,'lot_tag_id' => 77,'process_id' => 1],
            ['id'=> 388,'lot_tag_id' => 77,'process_id' => 12],
            ['id'=> 389,'lot_tag_id' => 77,'process_id' => 19],
            ['id'=> 390,'lot_tag_id' => 77,'process_id' => 14],
            ['id'=> 391,'lot_tag_id' => 77,'process_id' => 24],

            ['id'=> 392,'lot_tag_id' => 78,'process_id' => 119],
            ['id'=> 393,'lot_tag_id' => 78,'process_id' => 120],

            ['id'=> 394,'lot_tag_id' => 78,'process_id' => 19],
            ['id'=> 395,'lot_tag_id' => 78,'process_id' => 14],
            ['id'=> 396,'lot_tag_id' => 78,'process_id' => 24],

            ['id'=> 397,'lot_tag_id' => 79,'process_id' => 121],
            ['id'=> 398,'lot_tag_id' => 79,'process_id' => 12],
            ['id'=> 399,'lot_tag_id' => 79,'process_id' => 122],
            ['id'=> 400,'lot_tag_id' => 79,'process_id' => 112],
            ['id'=> 401,'lot_tag_id' => 79,'process_id' => 8],

            ['id'=> 402,'lot_tag_id' => 80,'process_id' => 123],
            ['id'=> 403,'lot_tag_id' => 80,'process_id' => 12],
            ['id'=> 404,'lot_tag_id' => 80,'process_id' => 7],
            ['id'=> 405,'lot_tag_id' => 80,'process_id' => 8],
            ['id'=> 406,'lot_tag_id' => 80,'process_id' => 14],

            ['id'=> 407,'lot_tag_id' => 81,'process_id' => 26],
            ['id'=> 408,'lot_tag_id' => 81,'process_id' => 41],
            ['id'=> 409,'lot_tag_id' => 81,'process_id' => 42],
            ['id'=> 410,'lot_tag_id' => 81,'process_id' => 43],

            ['id'=> 411,'lot_tag_id' => 82,'process_id' => 2],
            ['id'=> 412,'lot_tag_id' => 82,'process_id' => 7],
            ['id'=> 413,'lot_tag_id' => 82,'process_id' => 17],
            ['id'=> 414,'lot_tag_id' => 82,'process_id' => 27],

            ['id'=> 415,'lot_tag_id' => 83,'process_id' => 15],
            ['id'=> 416,'lot_tag_id' => 83,'process_id' => 16],
            ['id'=> 417,'lot_tag_id' => 83,'process_id' => 95],
            ['id'=> 418,'lot_tag_id' => 83,'process_id' => 40],

            ['id'=> 419,'lot_tag_id' => 84,'process_id' => 123],
            ['id'=> 420,'lot_tag_id' => 84,'process_id' => 12],
            ['id'=> 421,'lot_tag_id' => 84,'process_id' => 7],
            ['id'=> 422,'lot_tag_id' => 84,'process_id' => 8],
            ['id'=> 423,'lot_tag_id' => 84,'process_id' => 14],

            ['id'=> 424,'lot_tag_id' => 85,'process_id' => 1],
            ['id'=> 425,'lot_tag_id' => 85,'process_id' => 12],
            ['id'=> 426,'lot_tag_id' => 85,'process_id' => 7],
            ['id'=> 427,'lot_tag_id' => 85,'process_id' => 8],
            ['id'=> 428,'lot_tag_id' => 85,'process_id' => 14],

            ['id'=> 429,'lot_tag_id' => 86,'process_id' => 1],
            ['id'=> 430,'lot_tag_id' => 86,'process_id' => 16],
            ['id'=> 431,'lot_tag_id' => 86,'process_id' => 128],
            ['id'=> 432,'lot_tag_id' => 86,'process_id' => 14],

            ['id'=> 433,'lot_tag_id' => 87,'process_id' => 15],
            ['id'=> 434,'lot_tag_id' => 87,'process_id' => 22],
            ['id'=> 435,'lot_tag_id' => 87,'process_id' => 92],

            ['id'=> 436,'lot_tag_id' => 88,'process_id' => 1],
            ['id'=> 437,'lot_tag_id' => 88,'process_id' => 12],
            ['id'=> 438,'lot_tag_id' => 88,'process_id' => 7],
            ['id'=> 439,'lot_tag_id' => 88,'process_id' => 8],
            ['id'=> 440,'lot_tag_id' => 88,'process_id' => 14],

            ['id'=> 441,'lot_tag_id' => 89,'process_id' => 1],
            ['id'=> 442,'lot_tag_id' => 89,'process_id' => 12],
            ['id'=> 443,'lot_tag_id' => 89,'process_id' => 56],
            ['id'=> 444,'lot_tag_id' => 89,'process_id' => 130],

            ['id'=> 445,'lot_tag_id' => 90,'process_id' => 1],
            ['id'=> 446,'lot_tag_id' => 90,'process_id' => 2],
            ['id'=> 447,'lot_tag_id' => 90,'process_id' => 52],
            ['id'=> 448,'lot_tag_id' => 90,'process_id' => 131],
            ['id'=> 449,'lot_tag_id' => 90,'process_id' => 85],

            ['id'=> 450,'lot_tag_id' => 91,'process_id' => 1],
            ['id'=> 451,'lot_tag_id' => 91,'process_id' => 2],
            ['id'=> 452,'lot_tag_id' => 91,'process_id' => 52],
            ['id'=> 453,'lot_tag_id' => 91,'process_id' => 131],
            ['id'=> 454,'lot_tag_id' => 91,'process_id' => 85],
            ['id'=> 455,'lot_tag_id' => 91,'process_id' => 8],
            ['id'=> 456,'lot_tag_id' => 91,'process_id' => 11],

            ['id'=> 457,'lot_tag_id' => 92,'process_id' => 114],
            ['id'=> 458,'lot_tag_id' => 92,'process_id' => 12],
            ['id'=> 459,'lot_tag_id' => 92,'process_id' => 7],
            ['id'=> 460,'lot_tag_id' => 92,'process_id' => 8],
            ['id'=> 461,'lot_tag_id' => 92,'process_id' => 14],

            ['id'=> 462,'lot_tag_id' => 93,'process_id' => 114],
            ['id'=> 463,'lot_tag_id' => 93,'process_id' => 12],
            ['id'=> 464,'lot_tag_id' => 93,'process_id' => 7],
            ['id'=> 465,'lot_tag_id' => 93,'process_id' => 8],
            ['id'=> 466,'lot_tag_id' => 93,'process_id' => 14],

            ['id'=> 467,'lot_tag_id' => 94,'process_id' => 15],
            ['id'=> 468,'lot_tag_id' => 94,'process_id' => 16],
            ['id'=> 469,'lot_tag_id' => 94,'process_id' => 128],
            ['id'=> 470,'lot_tag_id' => 94,'process_id' => 132],
            ['id'=> 471,'lot_tag_id' => 94,'process_id' => 47],

            ['id'=> 472,'lot_tag_id' => 95,'process_id' => 15],
            ['id'=> 473,'lot_tag_id' => 95,'process_id' => 16],
            ['id'=> 474,'lot_tag_id' => 95,'process_id' => 128],
            ['id'=> 475,'lot_tag_id' => 95,'process_id' => 132],
            ['id'=> 476,'lot_tag_id' => 95,'process_id' => 47],

            ['id'=> 477,'lot_tag_id' => 96,'process_id' => 15],
            ['id'=> 478,'lot_tag_id' => 96,'process_id' => 16],
            ['id'=> 479,'lot_tag_id' => 96,'process_id' => 128],
            ['id'=> 480,'lot_tag_id' => 96,'process_id' => 132],
            ['id'=> 481,'lot_tag_id' => 96,'process_id' => 47],

            ['id'=> 482,'lot_tag_id' => 97,'process_id' => 15],
            ['id'=> 483,'lot_tag_id' => 97,'process_id' => 16],
            ['id'=> 484,'lot_tag_id' => 97,'process_id' => 128],
            ['id'=> 485,'lot_tag_id' => 97,'process_id' => 132],
            ['id'=> 486,'lot_tag_id' => 97,'process_id' => 47],
        
        );

        foreach($list as $key => $l){
            DB::table('lot_tag_process_file')->insert([
                'id' => $l['id'],
                'lot_tag_id' => $l['lot_tag_id'],
                'process_id' => $l['process_id'],
                'created_by' => 1,
                'created_at' => date('Y-m-d h:i:s')
            ]);
        }
    }
       
}
