<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use \Milon\Barcode\DNS1D;

class LottagsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $list = array(
            [   'id'=> 1,
                'part_no'=> '63722-TET-H000-50',
                'part_name'=> 'ADPE L RR COMBI',
                'model_id'=> 1,
                'type_id'=> 1,
                'material_id'=> 1,
                'material_t'=> '0.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 2,
                'part_no'=> '63322-TET-H000-50',
                'part_name'=> 'ADPT R RR COMBI',
                'model_id'=> 1,
                'type_id'=> 1,
                'material_id'=> 1,
                'material_t'=> '0.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 3,
                'part_no'=> '65685-TBA-A000-H1',
                'part_name'=> 'BRKT L FUEL TANK',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 2,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 4,
                'part_no'=> '61522-TBA-A000-H1',
                'part_name'=> 'C/MBR R DA/BD LWR',
                'model_id'=> 2,
                'type_id'=> 2,
                'material_id'=> 3,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 5,
                'part_no'=> '65667-TEA-T000-H1',
                'part_name'=> 'OUTRIGGER L RR FRM SIDE',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 6,
                'part_no'=> '65617-TEA-T000-H1',
                'part_name'=> 'OUTRIGGER R RR FRM SIDE',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 7,
                'part_no'=> '65667-TEZ-Y000-H1',
                'part_name'=> 'OUTRIGGER L RR FRM SIDE',
                'model_id'=> 3,
                'type_id'=> 4,
                'material_id'=> 3,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 8,
                'part_no'=> '65617-TEZ-Y000-H1',
                'part_name'=> 'OUTRIGGER R RR FRM SIDE',
                'model_id'=> 3,
                'type_id'=> 4,
                'material_id'=> 5,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 9,
                'part_no'=> '65776-TEA-T000-H1',
                'part_name'=> 'ANCHOR L RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 10,
                'part_no'=> '65726-TEA-T000-H1',
                'part_name'=> 'ANCHOR R RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 11,
                'part_no'=> '65776-TET-H000-H1',
                'part_name'=> 'ANCHOR L RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 1,
                'material_id'=> 6,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 12,
                'part_no'=> '65726-TET-H000-H1',
                'part_name'=> 'ANCHOR R RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 1,
                'material_id'=> 6,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 13,
                'part_no'=> '65776-TGG-A000-H1',
                'part_name'=> 'ANCHOR L RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 7,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 14,
                'part_no'=> '65726-TGG-A000-H1',
                'part_name'=> 'ANCHOR R RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 8,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 15,
                'part_no'=> '65683-TEA-T000-H1',
                'part_name'=> 'BRKT L RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 9,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 16,
                'part_no'=> '65633-TEA-T000-H1',
                'part_name'=> 'BRKT R RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 9,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 17,
                'part_no'=> '65669-TEZ-Y000-H1',
                'part_name'=> 'BRKT L BPR BEAM',
                'model_id'=> 3,
                'type_id'=> 4,
                'material_id'=> 10,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 18,
                'part_no'=> '65619-TEZ-Y000-H1',
                'part_name'=> 'BRKT R RR BPR BEAM',
                'model_id'=> 3,
                'type_id'=> 4,
                'material_id'=> 10,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 19,
                'part_no'=> '65674-TBA-A000-H1',
                'part_name'=> 'BRKT L TRG ARM',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 11,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 20,
                'part_no'=> '65624-TBA-A000-H1',
                'part_name'=> 'BRKT R TRG ARM',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 11,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 21,
                'part_no'=> '64336/736-TEA-T001-H1',
                'part_name'=> 'GST R/L RR SHELH RR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '0.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 22,
                'part_no'=> '66518-TBA-A000-H1',
                'part_name'=> 'ROD CHILD ANCHOR',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> 6.0,
                'material_rod'=> '178 MM.',
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014'
            ],
            [
                'id'=> 23,
                'part_no'=> '64735-TEA-T000-H1',
                'part_name'=> 'GST L SHELF FR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 13,
                'material_t'=> '0.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 24,
                'part_no'=> '64335-TEA-T000-H1',
                'part_name'=> 'GST R SHELF FR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 13,
                'material_t'=> '0.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 25,
                'part_no'=> '65687-TEA-T000-H1',
                'part_name'=> 'BRKT B L R RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 3,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 26,
                'part_no'=> '65637-TEA-T000-H1',
                'part_name'=> 'BRKT B R R RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 3,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 27,
                'part_no'=> '65736-TEX-Y001-H1',
                'part_name'=> 'PIOVT RR SEAT',
                'model_id'=> 1,
                'type_id'=> 4,
                'material_id'=> 14,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 28,
                'part_no'=> '65633/683-TEA-T000-H1',
                'part_name'=> 'BRKT R/L RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 9,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 29,
                'part_no'=> '61524-TEA-T000-H1',
                'part_name'=> 'STIFF R DA/BD L WR TUNNEL',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 15,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 30,
                'part_no'=> '61522-TET-H000-H1',
                'part_name'=> 'C/MBR R DA/BD LWR',
                'model_id'=> 1,
                'type_id'=> 1,
                'material_id'=> 4,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 31,
                'part_no'=> '65688-TEA-T000-H1',
                'part_name'=> 'BRKT C L RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 11,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'//345 จบ
            ],
            [
                'id'=> 32,
                'part_no'=> '65638-TEA-T001-H1',
                'part_name'=> 'BRKT C R RR SUB FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 11,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 33,
                'part_no'=> '65726/776-TEA-T000-H1',
                'part_name'=> 'ANCHOR R/L RR SEAT BELT',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 34,
                'part_no'=> '65745/795-TEA-T000-H1',
                'part_name'=> 'GST RR R/L RR BHD L WR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 35,
                'part_no'=> '64737-TEA-T000-H1',
                'part_name'=> 'GST L FRM FR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 36,
                'part_no'=> '64337-TEA-T000-H1',
                'part_name'=> 'GST R RR FRM FR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 37,
                'part_no'=> '65793-TEA-T000-H1',
                'part_name'=> 'GST FR L RR BHD LWR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 38,
                'part_no'=> '65743-TEA-T000-H1',
                'part_name'=> 'GST FR R RR BHD LWR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 39,
                'part_no'=> '65626/676-TBA-A001-H1',
                'part_name'=> 'GST R/L RR PNL',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 6,
                'material_t'=> '1.6', 
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 40,
                'part_no'=> '65696-TEZ-Y000-H1',
                'part_name'=> 'BRKT LWR RR BPR BEAM ',
                'model_id'=> 3,
                'type_id'=> 3,
                'material_id'=> 16,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'        
            ],
            [
                'id'=> 41,
                'part_no'=> '64745-TEA-T000-H1',
                'part_name'=> 'BRKT FILLER PIPE',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 11,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'    
            ],        
            [
                'id'=> 42,
                'part_no'=> '65693-TEA-T100-H1',
                'part_name'=> 'BRKT L JACK UP',
                'model_id'=> 1,
                'type_id'=> 5,
                'material_id'=> 14,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 43,
                'part_no'=> '65643-TEA-T100-H1',
                'part_name'=> 'BRKT R JACK UP',
                'model_id'=> 1,
                'type_id'=> 5,
                'material_id'=> 14,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 44,
                'part_no'=> '65748-TEA-T000-H1',
                'part_name'=> 'ROD CHILD ANCH CTR',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> 'ROD 135 MM.',
                'refer'=> null,
                'rev'=> '01',
                'rev_date'=> '15/8/2014'
            ],        
            [
                'id'=> 45,
                'part_no'=> '56749/799-TBA-A011-H1',
                'part_name'=> 'ROD R/L ANCHOR SIDE',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> 'ROD 180 MM.',
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014'
            ],        
            [
                'id'=> 46,
                'part_no'=> '65676-TGK-T000-H1',
                'part_name'=> 'GST L RR PNL',
                'model_id'=> 4,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 47,
                'part_no'=> '65626-TGK-T000-H1',
                'part_name'=> 'GST R RR PNL ',
                'model_id'=> 4,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],                       
            [
                'id'=> 48,
                'part_no'=> '65661-TEA-T000-50',
                'part_name'=> 'FRAME L REAR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 7,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 49,
                'part_no'=> '65611-TEA-T000-50',
                'part_name'=> 'FRAME R REAR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 7,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],                     
            [
                'id'=> 53,
                'part_no'=> '65726/776-TGG-A000-H1',
                'part_name'=> 'ANCHOR R/L RR SEAT BELT ',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 7,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],             
            [
                'id'=> 55,
                'part_no'=> '64351/751-TEA-T000-H1',
                'part_name'=> 'SUPPORT R/L RR SHELF',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 13,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                
                'id'=> 56,
                'part_no'=> '65689-TED-T000-H1',
                'part_name'=> 'BRKT L SLNCR MTG RR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 57,
                'part_no'=> '65639-TEA-T000-H1',
                'part_name'=> 'BRKT R SLNCK MTG RR',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 58,
                'part_no'=> '65672-TEA-T000-H1',
                'part_name'=> 'STIFF L RR FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 7,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 59,
                'part_no'=> '65622-TEA-T000-H1',
                'part_name'=> 'STIFF R RR FRAME',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 7,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 60,
                'part_no'=> '61165-TEZ-Y000-50',
                'part_name'=> 'W/SHIELD L WR FR',
                'model_id'=> 1,
                'type_id'=> 4,
                'material_id'=> 1,
                'material_t'=> '0.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 61,
                'part_no'=> '65696-TEA-T001-H1',
                'part_name'=> 'BRKT L WR RR BPR BEAM',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 13,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],
            [
                'id'=> 62,
                'part_no'=> '65642/692-TEZ-Y000-H1',
                'part_name'=> 'EXTN R/L C/MBR L WR',
                'model_id'=> 1,
                'type_id'=> 4,
                'material_id'=> 7,
                'material_t'=> '0.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'
            ],        
            [
                'id'=> 63,
                'part_no'=> '61524-TEZ-Y000-H1',
                'part_name'=> 'STIFF R DA/BD LWR TUNNEL',
                'model_id'=> 3,
                'type_id'=> 4,
                'material_id'=> 10,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017'//728
            ],
            [
                'id'=> 64,
                'part_no'=> '61121-TS6-H001-H1',
                'part_name'=> 'MBR R DA/BD UP SIDE',
                'model_id'=> 5,
                'type_id'=> 1,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 65,
                'part_no'=> '61126-TS6-H001-H1',
                'part_name'=> 'MBR L DA/BD UP SIDE',
                'model_id'=> 5,
                'type_id'=> 1,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 66,
                'part_no'=> '61517/518-TRD-A000',
                'part_name'=> 'GUSSET R/L DA/BD LWR SIDE',
                'model_id'=> 5,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 67,
                'part_no'=> '64351/751-TR3-A000-H1',
                'part_name'=> 'SUPPORT R/L RR SHELF',
                'model_id'=> 5,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 68,
                'part_no'=> '61551-TRO-NOOO-50',
                'part_name'=> 'C/MBR DA/BD LWR',
                'model_id'=> 6,
                'type_id'=> 6,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 69,
                'part_no'=> '64341/741-T8N-T000-H1',
                'part_name'=> 'PLR R/L RR INN UP',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 70,
                'part_no'=> '66115/155-T2A-A000-H1',
                'part_name'=> 'STIFF R/L RR PNL SIDE',
                'model_id'=> 9,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 71,
                'part_no'=> '65799-TEA-A000-H1',
                'part_name'=> 'ROD L CHILD ANCHOR SIDE',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 17,
                'material_t'=> '6.0',
                'material_rod'=> '180 MM.',
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 72,
                'part_no'=> '64714-T5L-T000-H1',
                'part_name'=> 'PLR L RR INN UP PLR',
                'model_id'=> 10,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 73,
                'part_no'=> '64334/734-TBA-A000-H1',
                'part_name'=> 'GST R/L RR SHELF SIDE',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 13,
                'material_t'=> '1.2',
                'material_rod'=> null,                
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 74,
                'part_no'=> '65749-TEA-A000-H1',
                'part_name'=> 'ROD R CHILD ANCHOR SIDE',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 17,
                'material_t'=> '6.0',
                'material_rod'=> '180 MM.',
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 75,
                'part_no'=> '65669-TEA-T000-H1',
                'part_name'=> 'BRKT L RR BPR BEAM',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 18,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 76,
                'part_no'=> '65619-TEA-T000-H1',
                'part_name'=> 'BRKT R RR BPR BEAM',
                'model_id'=> 1,
                'type_id'=> 3,
                'material_id'=> 18,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 77,
                'part_no'=> '64322/722-TBA-A000-H1',
                'part_name'=> 'GST R/L RR UPR INNER',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 13,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 78,
                'part_no'=> '65741-TGG-A000-H1',
                'part_name'=> 'C/MBR RR FLR UP',
                'model_id'=> 11,
                'type_id'=> 2,
                'material_id'=> 18,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 79,
                'part_no'=> '63521-T8N-P000-H1',
                'part_name'=> 'STIFF L FR PLR UP',
                'model_id'=> 8,
                'type_id'=> 7,
                'material_id'=> 12,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 80,
                'part_no'=> '64211-T8N-POO1-H1',
                'part_name'=> 'RAIL R ROOF SIDE FR',
                'model_id'=> 7,
                'type_id'=> 7,
                'material_id'=> 6,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 81,
                'part_no'=> '65749/799-TBA-A011-H1',
                'part_name'=> 'ROD R/L ANCHOR SIDE',
                'model_id'=> 1,
                'type_id'=> 2,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> 'ROD 180 MM.',
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 82,
                'part_no'=> '62112-T8R-T000-50',
                'part_name'=> 'STIFF FOOF PANEL FR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 83,
                'part_no'=> '61561-T8N-T000-H1',
                'part_name'=> 'PATCH DA/BD LWR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 84,
                'part_no'=> '64611-T8N-T100-H1',
                'part_name'=> 'RAIL L ROOF SIDE FR',
                'model_id'=> 7,
                'type_id'=> 5,
                'material_id'=> 12,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 85,
                'part_no'=> '64211-T8N-T000-H1',
                'part_name'=> 'RAIT R ROOF SIDE FR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 86,
                'part_no'=> '61122-T8N-T000-50',
                'part_name'=> 'BASE R HOOD HINGE',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 87,
                'part_no'=> '65193-T7T-M000-H1',
                'part_name'=> 'STIFF LWR L FR INSIDE SILL',
                'model_id'=> 8,
                'type_id'=> 9,
                'material_id'=> 12,
                'material_t'=> '2.3',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 88,
                'part_no'=> '64611-T8N-T000-H1',
                'part_name'=> 'RAIL L ROOF SIDE FR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 13,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '20/12/2017', 
            ],
            [
                'id'=> 89,
                'part_no'=> '61551-T8N-T000-H1',
                'part_name'=> 'C/MBR DA/BD LWR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 6,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014', 
            ],
            [
                'id'=> 90,
                'part_no'=> '66502-T9A-T000-H1',
                'part_name'=> 'C/MBR REAR SHELF',
                'model_id'=> 13,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 91,
                'part_no'=> '66502-T9A-T500-50',
                'part_name'=> 'C/MBR REAR SHELF',
                'model_id'=> 13,
                'type_id'=> 10,
                'material_id'=> 4,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '02',
                'rev_date'=> '20/12/2017',
            ],
            [
                'id'=> 92,
                'part_no'=> '64121-T8N-T000-H1',
                'part_name'=> 'PLR R FR INN UP',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 93,
                'part_no'=> '64121-T8N-P000-H1',
                'part_name'=> 'STIFF LWR R FR INSIDE SILL',
                'model_id'=> 12,
                'type_id'=> 7,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 94,
                'part_no'=> '65591-T8N-Y300-H1',
                'part_name'=> 'STIFF A L REAR FRAME UP',
                'model_id'=> 7,
                'type_id'=> 11,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 95,
                'part_no'=> '65541-T8N-Y300-H1',
                'part_name'=> 'SITFF A R REAR FRAME UP',
                'model_id'=> 7,
                'type_id'=> 11,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 96,
                'part_no'=> '65541-T8N-T600-H1',
                'part_name'=> 'SITFF A R REAR FRAME UP',
                'model_id'=> 7,
                'type_id'=> 12,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 97,
                'part_no'=> '65591-T8N-T600-H1',
                'part_name'=> 'SITFF A L REAR FRAME UP',
                'model_id'=> 7,
                'type_id'=> 12,
                'material_id'=> 12,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 98,
                'part_no'=> '62115-T8R-T000-H1',
                'part_name'=> 'STIFF R ROOF PANEL FR CORNEF',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 99,
                'part_no'=> '62165-T8R-T000-H1',
                'part_name'=> 'STIFF L ROOF PANEL FR CORNEF',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 100,
                'part_no'=> '61127-T8N-T000-H1',
                'part_name'=> 'BASE L HOOD HINGE',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 101,
                'part_no'=> '64212-T8N-T000-H1',
                'part_name'=> 'RAIL R ROOF SIDE RR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 102,
                'part_no'=> '64612-T8N-T000-H1',
                'part_name'=> 'RAIL L ROOF SIDE RR',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 103,
                'part_no'=> '61142-T8N-T000-50',
                'part_name'=> 'RNFCT R FR DPRBASE',
                'model_id'=> 7,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 104,
                'part_no'=> '65165-T9A-Y000-50',
                'part_name'=> 'STIFF FR FLR PNL FR',
                'model_id'=> 14,
                'type_id'=> 4,
                'material_id'=> 12,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 105,
                'part_no'=> '65165-T5H-H000-50',
                'part_name'=> 'STIFF FR FLR PNL FR',
                'model_id'=> 10,
                'type_id'=> 1,
                'material_id'=> 12,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 106,
                'part_no'=> '65165-T5L-T000-50',
                'part_name'=> 'STIFF FR FLR PNL FR',
                'model_id'=> 10,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 107,
                'part_no'=> '63121-T5L-T000-H1',
                'part_name'=> 'STIFF R FR PLR UP',
                'model_id'=> 10,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 108,
                'part_no'=> '66117/157-T9A-T000-H1',
                'part_name'=> 'STIFF R/L RR PNL SIDE',
                'model_id'=> 13,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '0.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 109,
                'part_no'=> '63223/623-T9A-T000-H1',
                'part_name'=> 'BHD R/L SIDE SILL STIFF FR END',
                'model_id'=> 13,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '1.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 110,
                'part_no'=> '65133-TOA-K000-H1',
                'part_name'=> 'STIFF RR FLR C/MBR',
                'model_id'=> 15,
                'type_id'=> 14,
                'material_id'=> 12,
                'material_t'=> '1.2',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 111,
                'part_no'=> '64521-TRD-P000-H1',
                'part_name'=> 'PLR L FR INN UP',
                'model_id'=> 5,
                'type_id'=> 7,
                'material_id'=> 12,
                'material_t'=> '1.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 112,
                'part_no'=> '62112-TOT-H000-H1',
                'part_name'=> 'STIFF ROOF PANEL',
                'model_id'=> 15,
                'type_id'=> 1,
                'material_id'=> 12,
                'material_t'=> '0.7',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 113,
                'part_no'=> '61553-TOA-3000',
                'part_name'=> 'BRKT ACCEL PEDAL',
                'model_id'=> 15,
                'type_id'=> 15,
                'material_id'=> 12,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 114,
                'part_no'=> '61111-TG1-P000-50',
                'part_name'=> 'DASHBOARD UPPER',
                'model_id'=> 16,
                'type_id'=> 7,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 115,
                'part_no'=> '62112-TME-T200-H1',
                'part_name'=> 'STIFF ROOF PANEL FR',
                'model_id'=> 17,
                'type_id'=> 16,
                'material_id'=> 4,
                'material_t'=> '1.6',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014', 
            ],
            [
                'id'=> 116,
                'part_no'=> '65751-TME-T000-H1',
                'part_name'=> 'C/MBR RAER FLOOR',
                'model_id'=> 17,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> '2.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 117,
                'part_no'=> '65751-TMH-T001-H1',
                'part_name'=> 'C/MBR REAR FLOOR',
                'model_id'=> 17,
                'type_id'=> 3,
                'material_id'=> 4,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 118,
                'part_no'=> '64312/712-T9A-T000-H1',
                'part_name'=> 'SUPPORT R/L SHELF',
                'model_id'=> 13,
                'type_id'=> 3,
                'material_id'=> 12,
                'material_t'=> null,
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 119,
                'part_no'=> '65165-T9A-X000-H1',
                'part_name'=> 'STIFF FR FLR PNL FR',
                'model_id'=> 18,
                'type_id'=> 17,
                'material_id'=> 19,
                'material_t'=> '1.4',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 120,
                'part_no'=> '61551-T5H-H000-50',
                'part_name'=> 'C/MBR DA/BD L WR',
                'model_id'=> 10,
                'type_id'=> 1,
                'material_id'=> 12,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 121,
                'part_no'=> '66112-T5A-3003',
                'part_name'=> 'STIFF RR PNL UP',
                'model_id'=> 10,
                'type_id'=> 15,
                'material_id'=> 12,
                'material_t'=> '0.8',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
            [
                'id'=> 122,
                'part_no'=> '65117/167-T5A-3000',
                'part_name'=> 'C/MBR R/L FR FLR PNL FR',
                'model_id'=> 13,
                'type_id'=> 15,
                'material_id'=> 12,
                'material_t'=> '1.0',
                'material_rod'=> null,
                'refer'=> 'FM-QA-33',
                'rev'=> '01',
                'rev_date'=> '15/8/2014',
            ],
        );



        foreach($list as $key => $l){

            $d = new DNS1D();
            $d->setStorPath(__DIR__."/cache/");
            $bar_code = 'data:image/png;base64,'.$d->getBarcodePNG(str_replace('-','',$l['part_no']), "C128");
            $id_barcode = DB::table('qbar_code')->insertGetId([
                'filebase64' => $bar_code,
                'created_by' => 1,
                'created_at' => date('Y-m-d h:i:s')
            ]);

            DB::table('lkup_lot_tag')->insert([
                'id' => $l['id'],
                'part_no' => $l['part_no'],
                'part_name' => $l['part_name'],
                'model_id' => $l['model_id'],
                'type_id' => $l['type_id'],
                'material_id' => $l['material_id'],
                'material_t' => $l['material_t'],
                'material_rod' => $l['material_rod'],
                'refer' => $l['refer'],
                'rev' => $l['rev'],
                'rev_date' => $l['rev_date'],
                'barcode_id' => $id_barcode,
                'created_by' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'is_enable' => 'Y',
            ]);
        }
    }
}
